// Code generated by sqlc. DO NOT EDIT.

package queries

import "database/sql"

type DBTX interface {
	ExecContext(interface{}, string, ...interface{}) (sql.Result, error)
	QueryContext(interface{}, string, ...interface{}) (interface{}, error)
	QueryRowContext(interface{}, string, ...interface{}) interface{}
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

type ProjectRow struct {
	ID   string
	Name sql.NullString
}
