// Code generated by sqlc. DO NOT EDIT.
// source: fixture.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

// CountProjects: no-arg, int64 return
const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

// DeleteProject: no-arg struct param, exec (nil) return (mutating)
const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

// GetProject: single string arg, row return
const getProject = `-- name: GetProject :one
SELECT id, name FROM projects WHERE id = ?`

func (q *Queries) GetProject(ctx context.Context, id string) (ProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var p ProjectRow
	err := row.Scan(&p.ID, &p.Name)
	return p, err
}

// ListProjects: no-arg, list return
const listProjects = `-- name: ListProjects :many
SELECT id, name FROM projects`

func (q *Queries) ListProjects(ctx context.Context) ([]ProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectRow
	for rows.Next() {
		var p ProjectRow
		if err := rows.Scan(&p.ID, &p.Name); err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}

// ListProjectIDs: no-arg, []string return
const listProjectIDs = `-- name: ListProjectIDs :many
SELECT id FROM projects`

func (q *Queries) ListProjectIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	return items, rows.Err()
}

// CreateProject: struct param, execresult return (mutating)
const createProject = `-- name: CreateProject :execresult
INSERT INTO projects (id, name, owner_id, created_at) VALUES (?, ?, ?, now())`

type CreateProjectParams struct {
	ID        string
	Name      string
	OwnerID   string
	CreatedAt time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProject, arg.ID, arg.Name, arg.OwnerID, arg.CreatedAt)
}

// UpdateProjectName: struct param with NullString, nil return (mutating)
const updateProjectName = `-- name: UpdateProjectName :exec
UPDATE projects SET name = ? WHERE id = ?`

type UpdateProjectNameParams struct {
	Name sql.NullString
	ID   string
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectName, arg.Name, arg.ID)
	return err
}

// GetProjectByType: single arg whose name is a reserved word
const getProjectByType = `-- name: GetProjectByType :one
SELECT id, name FROM projects WHERE type = ?`

func (q *Queries) GetProjectByType(ctx context.Context, type_ string) (ProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByType, type_)
	var p ProjectRow
	err := row.Scan(&p.ID, &p.Name)
	return p, err
}
