// Code generated by sqlc-cobra v0.1.0 (https://github.com/sat0yu/sqlc-cobra)
// DO NOT EDIT.

package sqlc

import (
	"fmt"

	"github.com/sat0yu/sqlc-cobra/examples/mysql/queries"
	runtime "github.com/sat0yu/sqlc-cobra/runtime"
	"github.com/spf13/cobra"
)

var _ = fmt.Sprint  // keep fmt referenced
var _ = queries.New // keep queries referenced

func init() {
	cmd := &cobra.Command{
		Use:   "CountDevices",
		Short: "Calls Queries.CountDevices",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			n, err := q.CountDevices(ctx)
			if err != nil {
				return err
			}
			return runtime.PrintInt64(runtime.Stdout, n)
		},
	}
	SqlcCmd.AddCommand(cmd)
}

func init() {
	cmd := &cobra.Command{
		Use:   "CountProjects",
		Short: "Calls Queries.CountProjects",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			n, err := q.CountProjects(ctx)
			if err != nil {
				return err
			}
			return runtime.PrintInt64(runtime.Stdout, n)
		},
	}
	SqlcCmd.AddCommand(cmd)
}

const createDeviceSQL = "-- name: CreateDevice :execresult\nINSERT INTO devices (id, project_id, name) VALUES (?, ?, ?)"

func init() {
	cmd := &cobra.Command{
		Use:   "CreateDevice",
		Short: "Calls Queries.CreateDevice",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			iD, _ := cmd.Flags().GetString("id")
			projectID, _ := cmd.Flags().GetString("project-id")
			name, _ := cmd.Flags().GetString("name")
			params := queries.CreateDeviceParams{
				ID:        iD,
				ProjectID: projectID,
				Name:      name,
			}
			if err := (runtime.Prompt{In: runtime.Stdin, Out: runtime.Stderr}).ConfirmMutation(cmd, createDeviceSQL, []any{params.ID, params.ProjectID, params.Name}); err != nil {
				return err
			}
			res, err := q.CreateDevice(ctx, params)
			if err != nil {
				return err
			}
			return runtime.PrintExecResult(runtime.Stdout, res)
		},
	}
	cmd.Flags().String("id", "", "ID")
	cmd.MarkFlagRequired("id")
	cmd.Flags().String("project-id", "", "ProjectID")
	cmd.MarkFlagRequired("project-id")
	cmd.Flags().String("name", "", "Name")
	cmd.MarkFlagRequired("name")
	SqlcCmd.AddCommand(cmd)
}

const createProjectSQL = "-- name: CreateProject :execresult\nINSERT INTO projects (id, name, owner_id) VALUES (?, ?, ?)"

func init() {
	cmd := &cobra.Command{
		Use:   "CreateProject",
		Short: "Calls Queries.CreateProject",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			iD, _ := cmd.Flags().GetString("id")
			name, _ := cmd.Flags().GetString("name")
			ownerID, _ := cmd.Flags().GetString("owner-id")
			params := queries.CreateProjectParams{
				ID:      iD,
				Name:    name,
				OwnerID: ownerID,
			}
			if err := (runtime.Prompt{In: runtime.Stdin, Out: runtime.Stderr}).ConfirmMutation(cmd, createProjectSQL, []any{params.ID, params.Name, params.OwnerID}); err != nil {
				return err
			}
			res, err := q.CreateProject(ctx, params)
			if err != nil {
				return err
			}
			return runtime.PrintExecResult(runtime.Stdout, res)
		},
	}
	cmd.Flags().String("id", "", "ID")
	cmd.MarkFlagRequired("id")
	cmd.Flags().String("name", "", "Name")
	cmd.MarkFlagRequired("name")
	cmd.Flags().String("owner-id", "", "OwnerID")
	cmd.MarkFlagRequired("owner-id")
	SqlcCmd.AddCommand(cmd)
}

const deleteDeviceSQL = "-- name: DeleteDevice :exec\nDELETE FROM devices WHERE id = ?"

func init() {
	cmd := &cobra.Command{
		Use:   "DeleteDevice <id>",
		Short: "Calls Queries.DeleteDevice",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			id := args[0]
			if err := (runtime.Prompt{In: runtime.Stdin, Out: runtime.Stderr}).ConfirmMutation(cmd, deleteDeviceSQL, []any{id}); err != nil {
				return err
			}
			if err := q.DeleteDevice(ctx, id); err != nil {
				return err
			}
			return runtime.PrintOK(runtime.Stdout)
		},
	}
	SqlcCmd.AddCommand(cmd)
}

const deleteProjectSQL = "-- name: DeleteProject :exec\nDELETE FROM projects WHERE id = ?"

func init() {
	cmd := &cobra.Command{
		Use:   "DeleteProject <id>",
		Short: "Calls Queries.DeleteProject",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			id := args[0]
			if err := (runtime.Prompt{In: runtime.Stdin, Out: runtime.Stderr}).ConfirmMutation(cmd, deleteProjectSQL, []any{id}); err != nil {
				return err
			}
			if err := q.DeleteProject(ctx, id); err != nil {
				return err
			}
			return runtime.PrintOK(runtime.Stdout)
		},
	}
	SqlcCmd.AddCommand(cmd)
}

func init() {
	cmd := &cobra.Command{
		Use:   "GetDevice <id>",
		Short: "Calls Queries.GetDevice",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			id := args[0]
			row, err := q.GetDevice(ctx, id)
			if err != nil {
				return err
			}
			return runtime.PrintJSON(runtime.Stdout, row)
		},
	}
	SqlcCmd.AddCommand(cmd)
}

func init() {
	cmd := &cobra.Command{
		Use:   "GetProject <id>",
		Short: "Calls Queries.GetProject",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			id := args[0]
			row, err := q.GetProject(ctx, id)
			if err != nil {
				return err
			}
			return runtime.PrintJSON(runtime.Stdout, row)
		},
	}
	SqlcCmd.AddCommand(cmd)
}

func init() {
	cmd := &cobra.Command{
		Use:   "ListDevices <projectID>",
		Short: "Calls Queries.ListDevices",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			projectID := args[0]
			rows, err := q.ListDevices(ctx, projectID)
			if err != nil {
				return err
			}
			return runtime.PrintJSON(runtime.Stdout, rows)
		},
	}
	SqlcCmd.AddCommand(cmd)
}

func init() {
	cmd := &cobra.Command{
		Use:   "ListProjects",
		Short: "Calls Queries.ListProjects",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := runtime.CmdContext(cmd)
			q, cleanup, err := openQueries()
			if err != nil {
				return err
			}
			defer cleanup()
			rows, err := q.ListProjects(ctx)
			if err != nil {
				return err
			}
			return runtime.PrintJSON(runtime.Stdout, rows)
		},
	}
	SqlcCmd.AddCommand(cmd)
}
