// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, owner_id, created_at FROM projects WHERE id = ?`

type GetProjectRow struct {
	ID        string
	Name      string
	OwnerID   string
	CreatedAt time.Time
}

func (q *Queries) GetProject(ctx context.Context, id string) (GetProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var p GetProjectRow
	err := row.Scan(&p.ID, &p.Name, &p.OwnerID, &p.CreatedAt)
	return p, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, owner_id, created_at FROM projects`

type ListProjectsRow struct {
	ID        string
	Name      string
	OwnerID   string
	CreatedAt time.Time
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var p ListProjectsRow
		if err := rows.Scan(&p.ID, &p.Name, &p.OwnerID, &p.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}

const createProject = `-- name: CreateProject :execresult
INSERT INTO projects (id, name, owner_id) VALUES (?, ?, ?)`

type CreateProjectParams struct {
	ID      string
	Name    string
	OwnerID string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProject, arg.ID, arg.Name, arg.OwnerID)
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) FROM devices`

func (q *Queries) CountDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, project_id, name, created_at FROM devices WHERE id = ?`

type GetDeviceRow struct {
	ID        string
	ProjectID string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) GetDevice(ctx context.Context, id string) (GetDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var d GetDeviceRow
	err := row.Scan(&d.ID, &d.ProjectID, &d.Name, &d.CreatedAt)
	return d, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, project_id, name, created_at FROM devices WHERE project_id = ?`

type ListDevicesRow struct {
	ID        string
	ProjectID string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) ListDevices(ctx context.Context, projectID string) ([]ListDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesRow
	for rows.Next() {
		var d ListDevicesRow
		if err := rows.Scan(&d.ID, &d.ProjectID, &d.Name, &d.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, d)
	}
	return items, rows.Err()
}

const createDevice = `-- name: CreateDevice :execresult
INSERT INTO devices (id, project_id, name) VALUES (?, ?, ?)`

type CreateDeviceParams struct {
	ID        string
	ProjectID string
	Name      string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDevice, arg.ID, arg.ProjectID, arg.Name)
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?`

func (q *Queries) DeleteDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}
